<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 F:\Users\dgode\Documents\JS\threlte-seq\static\models\amethyst_crystal.glb --root /models/ --types --printwidth 120 --precision 2
Author: Eydeet (https://sketchfab.com/eydeet)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/amethyst-crystal-ace99fb589734464bda00687bbcedc6d
Title: Amethyst Crystal
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      amethyst_1k_amethyst_1k_u1_v1_0: THREE.Mesh
    }
    materials: {
      amethyst_1k_u1_v1: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/amethyst_crystal.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={1}>
      <T.Mesh
        geometry={gltf.nodes.amethyst_1k_amethyst_1k_u1_v1_0.geometry}
        material={gltf.materials.amethyst_1k_u1_v1}
        scale={1}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
