<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 F:\Users\dgode\Documents\JS\threlte-seq\static\models\goldfish.glb --root /models/ --types --printwidth 120 --precision 2
Author: Jean-Christophe Sekinger (https://sketchfab.com/jc.sekinger)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/goldfish-071e439aee854058946e537949bf665e
Title: Goldfish
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Object_4: THREE.Mesh
    }
    materials: {
      Goldfish: THREE.MeshPhysicalMaterial
    }
  }

  export const gltf = useGltf<GLTFResult>('/models/goldfish.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
      <T.Mesh
        geometry={gltf.nodes.Object_4.geometry}
        material={gltf.materials.Goldfish}
        rotation={[0, 0, 0]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
