<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 F:\Users\dgode\Documents\JS\threlte-seq\static\models\the_fish_particle.glb --root /models/ --types --printwidth 120 --precision 2
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-fish-particle-eb214794846949a5a0b1af75fd649aa2
Title: The Fish Particle
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'
  import {MeshStandardMaterial} from 'three'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Take 01'
  type GLTFResult = {
    nodes: {
      particle049_0: THREE.Mesh
      particle049_0_1: THREE.Mesh
      particle049_0_2: THREE.Mesh
      particle049_0_3: THREE.Mesh
      particle049_0_4: THREE.Mesh
      particle049_0_5: THREE.Mesh
      particle049_0_6: THREE.Mesh
      particle049_0_7: THREE.Mesh
      particle049_0_8: THREE.Mesh
      particle049_0_9: THREE.Mesh
      particle049_0_10: THREE.Mesh
      particle049_0_11: THREE.Mesh
      particle049_0_12: THREE.Mesh
      particle049_0_13: THREE.Mesh
      particle049_0_14: THREE.Mesh
      particle049_0_15: THREE.Mesh
      particle049_0_16: THREE.Mesh
      particle049_0_17: THREE.Mesh
      particle049_0_18: THREE.Mesh
      particle049_0_19: THREE.Mesh
      particle049_0_20: THREE.Mesh
      particle049_0_21: THREE.Mesh
      particle049_0_22: THREE.Mesh
      particle049_0_23: THREE.Mesh
      particle049_0_24: THREE.Mesh
      particle049_0_25: THREE.Mesh
      particle049_0_26: THREE.Mesh
      particle049_0_27: THREE.Mesh
      particle049_0_28: THREE.Mesh
      particle049_0_29: THREE.Mesh
      particle049_0_30: THREE.Mesh
      particle049_0_31: THREE.Mesh
      particle049_0_32: THREE.Mesh
      particle049_0_33: THREE.Mesh
      particle049_0_34: THREE.Mesh
      particle049_0_35: THREE.Mesh
      particle049_0_36: THREE.Mesh
      particle049_0_37: THREE.Mesh
      particle049_0_38: THREE.Mesh
      particle049_0_39: THREE.Mesh
      particle049_0_40: THREE.Mesh
      particle049_0_41: THREE.Mesh
      particle049_0_42: THREE.Mesh
      particle049_0_43: THREE.Mesh
      particle049_0_44: THREE.Mesh
      particle049_0_45: THREE.Mesh
      particle049_0_46: THREE.Mesh
      particle049_0_47: THREE.Mesh
      particle049_0_48: THREE.Mesh
      particle049_0_49: THREE.Mesh
    }
    materials: {
      Root: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/the_fish_particle.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

    const component = forwardEventHandlers()
    // $: $actions['Take 01']?.reset().fadeIn(0.5).play()
    $: $actions['Take 01']?.play().setDuration(7.7)
    const rootMaterial = new MeshStandardMaterial({
      color: 0xffffff,
      transparent: true,
      opacity: 1,
      metalness: 0.1,
      roughness: 0.1

    })
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} castShadow>
        <T.Group name="Root">
          <T.Group name="particle000" position={[1.13, 1.23, 1.21]} rotation={[0.04, -0.08, 1.77]} scale={0.07}>
            <T.Mesh name="particle049_0" geometry={gltf.nodes.particle049_0.geometry} material={rootMaterial} />
          </T.Group>
          <T.Group name="particle001" position={[1.13, 1.02, 0.44]} rotation={[0.11, Math.random(), 1.74]} scale={0.05}>
            <T.PointLight color={0xaa00ff} intensity={1} />
            <T.Mesh
            name="particle049_0_1"
            geometry={gltf.nodes.particle049_0_1.geometry}
            material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle002" position={[0.96, 0.74, 0.71]} rotation={[0.13, 0.09, 1.2]} scale={0.08}>
            <T.PointLight color={0xaaaa00} intensity={0.5} />
            <T.Mesh
            name="particle049_0_2"
            geometry={gltf.nodes.particle049_0_2.geometry}
            material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle003" position={[0.8, 0.39, 0.48]} rotation={[0.06, Math.random(), 1.78]} scale={0.05}>
            <T.PointLight color={0x0055aa} intensity={1} />
            <T.Mesh
            name="particle049_0_3"
            geometry={gltf.nodes.particle049_0_3.geometry}
            material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle004" position={[1.46, 1.14, 0.82]} rotation={[0.01, Math.random(), 1.65]} scale={0.07}>
            <T.PointLight color={0x00ff00} intensity={0.5} />
            <T.Mesh
            name="particle049_0_4"
            geometry={gltf.nodes.particle049_0_4.geometry}
            material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle005" position={[0.77, -0.01, 1.31]} rotation={[0.01, Math.random(), 1.63]} scale={0.08}>
            <T.PointLight color={0xaa00ff} intensity={0.5} />
            <T.Mesh
            name="particle049_0_5"
            geometry={gltf.nodes.particle049_0_5.geometry}
            material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle006" position={[1.33, 0.7, 0.9]} rotation={[0.06, Math.random(), 1.33]} scale={0.06}>
            <T.PointLight color={0xaaaa00} intensity={1} />
            <T.Mesh
            name="particle049_0_6"
            geometry={gltf.nodes.particle049_0_6.geometry}
            material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle007" position={[1.06, 0.01, 0.35]} rotation={[0.15, Math.random()*  Date.now(), 0.78]} scale={0.06}>
            <T.PointLight color={0x0055aa} intensity={0.5} />
            <T.Mesh
            name="particle049_0_7"
              geometry={gltf.nodes.particle049_0_7.geometry}
              material={rootMaterial}
              />
            </T.Group>
            <T.Group name="particle008" position={[0.8, 0.88, 0.28]} rotation={[0,Math.random()* Date.now(), 1.32]} scale={0.06}>
              <T.PointLight color={0x00ff00} intensity={0.5} />
              <T.Mesh
              name="particle049_0_8"
              geometry={gltf.nodes.particle049_0_8.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle009" position={[0.96, 0.74, 1.17]} rotation={[0.11, Math.random(), 1.66]} scale={0.07}>
            <T.Mesh
              name="particle049_0_9"
              geometry={gltf.nodes.particle049_0_9.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle010" position={[0.44, 0.18, 0.37]} rotation={[0.35, Math.random(), 0.27]} scale={0.08}>
            <T.Mesh
              name="particle049_0_10"
              geometry={gltf.nodes.particle049_0_10.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle011" position={[1.23, 0.45, 0.51]} rotation={[0.05, Math.random(), 1.4]} scale={0.05}>
            <T.Mesh
              name="particle049_0_11"
              geometry={gltf.nodes.particle049_0_11.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle012" position={[1.08, 0.57, 0.09]} rotation={[0.09, Math.random(), 2.12]} scale={0.06}>
            <T.Mesh
              name="particle049_0_12"
              geometry={gltf.nodes.particle049_0_12.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle013" position={[1.38, 1.46, 0.38]} rotation={[0.08, Math.random(), 1.71]} scale={0.07}>
            <T.Mesh
              name="particle049_0_13"
              geometry={gltf.nodes.particle049_0_13.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle014" position={[0.22, 0.12, 0.92]} rotation={[0.08,Math.random(), 1.48]} scale={0.07}>
            <T.Mesh
              name="particle049_0_14"
              geometry={gltf.nodes.particle049_0_14.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle015" position={[1.06, 0.25, 0.92]} rotation={[0.1, 0.09, 1.05]} scale={0.05}>
            <T.Mesh
              name="particle049_0_15"
              geometry={gltf.nodes.particle049_0_15.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle017" position={[0.59, 0.77, 0.59]} rotation={[0.06, 0.08, 1.03]} scale={0.07}>
            <T.Mesh
              name="particle049_0_16"
              geometry={gltf.nodes.particle049_0_16.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle018" position={[0.66, 0.44, 0.92]} rotation={[0.13, 0.02, 0.81]} scale={0.05}>
            <T.Mesh
              name="particle049_0_17"
              geometry={gltf.nodes.particle049_0_17.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle019" position={[1.07, 1, -0.05]} rotation={[0.12, 0.19, 1.06]} scale={0.06}>
            <T.Mesh
              name="particle049_0_18"
              geometry={gltf.nodes.particle049_0_18.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle020" position={[1.72, 0.49, 0.78]} rotation={[0.18, -0.09, 1.94]} scale={0.06}>
            <T.Mesh
              name="particle049_0_19"
              geometry={gltf.nodes.particle049_0_19.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle021" position={[0.53, -0.32, 0.46]} rotation={[0.12, 0.09, 0.91]} scale={0.07}>
            <T.Mesh
              name="particle049_0_20"
              geometry={gltf.nodes.particle049_0_20.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle022" position={[0.97, 1.38, 0.27]} rotation={[0.29, -0.11, 2.84]} scale={0.06}>
            <T.Mesh
              name="particle049_0_21"
              geometry={gltf.nodes.particle049_0_21.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle023" position={[0.88, -0.35, 0.09]} rotation={[0.15, 0.06, 0.75]} scale={0.08}>
            <T.Mesh
              name="particle049_0_22"
              geometry={gltf.nodes.particle049_0_22.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle024" position={[0.78, -0.09, 0.78]} rotation={[-0.01, -0.03, 1.5]} scale={0.06}>
            <T.Mesh
              name="particle049_0_23"
              geometry={gltf.nodes.particle049_0_23.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle025" position={[1.5, 0.75, 0.46]} rotation={[0.02, -0.07, 1.81]} scale={0.06}>
            <T.Mesh
              name="particle049_0_24"
              geometry={gltf.nodes.particle049_0_24.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle026" position={[0.43, 0.41, 1.37]} rotation={[0.08, -0.04, 1.31]} scale={0.06}>
            <T.Mesh
              name="particle049_0_25"
              geometry={gltf.nodes.particle049_0_25.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle027" position={[0.88, 1.21, 0.74]} rotation={[0.18, -0.09, 2]} scale={0.05}>
            <T.Mesh
              name="particle049_0_26"
              geometry={gltf.nodes.particle049_0_26.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle028" position={[0.51, 0.87, 1.06]} rotation={[0.02, 0, 1.47]} scale={0.05}>
            <T.Mesh
              name="particle049_0_27"
              geometry={gltf.nodes.particle049_0_27.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle029" position={[0.51, -0.7, 0.97]} rotation={[0.15, -0.14, 2]} scale={0.06}>
            <T.Mesh
              name="particle049_0_28"
              geometry={gltf.nodes.particle049_0_28.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle030" position={[0.2, -0.64, 0.32]} rotation={[0.38, -0.08, 0.45]} scale={0.06}>
            <T.Mesh
              name="particle049_0_29"
              geometry={gltf.nodes.particle049_0_29.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle031" position={[0.75, -0.5, 1.46]} rotation={[0.17, 0.17, 0.75]} scale={0.08}>
            <T.Mesh
              name="particle049_0_30"
              geometry={gltf.nodes.particle049_0_30.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle032" position={[0.38, 0.51, 0.57]} rotation={[0.03, 0.12, 0.56]} scale={0.05}>
            <T.Mesh
              name="particle049_0_31"
              geometry={gltf.nodes.particle049_0_31.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle016" position={[1.37, 0.41, 1.32]} rotation={[0.05, -0.21, 1.58]} scale={0.07}>
            <T.Mesh
              name="particle049_0_32"
              geometry={gltf.nodes.particle049_0_32.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle033" position={[0.13, -0.09, 0.53]} rotation={[0.01, -0.03, 1.11]} scale={0.06}>
            <T.Mesh
              name="particle049_0_33"
              geometry={gltf.nodes.particle049_0_33.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle034" position={[1.51, -0.01, 0.66]} rotation={[0.05, -0.05, 1.41]} scale={0.06}>
            <T.Mesh
              name="particle049_0_34"
              geometry={gltf.nodes.particle049_0_34.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle035" position={[1.16, -0.48, 0.34]} rotation={[0.03, 0.07, 1.24]} scale={0.07}>
            <T.Mesh
              name="particle049_0_35"
              geometry={gltf.nodes.particle049_0_35.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle036" position={[-0.08, 0.43, 1.11]} rotation={[0, -0.04, 1.21]} scale={0.06}>
            <T.Mesh
              name="particle049_0_36"
              geometry={gltf.nodes.particle049_0_36.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle037" position={[0.08, 0.54, 0.26]} rotation={[-0.06, -0.02, 1.15]} scale={0.06}>
            <T.Mesh
              name="particle049_0_37"
              geometry={gltf.nodes.particle049_0_37.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle038" position={[0.5, -0.07, 0.04]} rotation={[0.07, 0.13, 0.93]} scale={0.06}>
            <T.Mesh
              name="particle049_0_38"
              geometry={gltf.nodes.particle049_0_38.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle039" position={[-0.27, -0.24, 0.34]} rotation={[0.14, 0.07, 1.42]} scale={0.06}>
            <T.Mesh
              name="particle049_0_39"
              geometry={gltf.nodes.particle049_0_39.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle040" position={[1.25, -0.47, 1.02]} rotation={[0.05, -0.01, 1.3]} scale={0.07}>
            <T.Mesh
              name="particle049_0_40"
              geometry={gltf.nodes.particle049_0_40.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle041" position={[0.97, 0.4, 1.67]} rotation={[-0.02, -0.15, 1.63]} scale={0.07}>
            <T.Mesh
              name="particle049_0_41"
              geometry={gltf.nodes.particle049_0_41.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle042" position={[-0.4, -0.55, 0.84]} rotation={[0.03, -0.05, 0.72]} scale={0.05}>
            <T.Mesh
              name="particle049_0_42"
              geometry={gltf.nodes.particle049_0_42.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle049" position={[-0.91, -1.45, 1.39]} rotation={[-0.05, 0.06, 0.74]} scale={0.06}>
            <T.Mesh
              name="particle049_0_43"
              geometry={gltf.nodes.particle049_0_43.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle043" position={[0.5, -1.04, 1.6]} rotation={[-0.06, -0.18, 2]} scale={0.07}>
            <T.Mesh
              name="particle049_0_44"
              geometry={gltf.nodes.particle049_0_44.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle044" position={[-0.33, -1, 1.68]} rotation={[-0.05, 0.03, 0.97]} scale={0.08}>
            <T.Mesh
              name="particle049_0_45"
              geometry={gltf.nodes.particle049_0_45.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle045" position={[0.89, -1.45, 1.15]} rotation={[-0.1, 0.02, 1.45]} scale={0.06}>
            <T.Mesh
              name="particle049_0_46"
              geometry={gltf.nodes.particle049_0_46.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle046" position={[0.55, -0.93, -0.08]} rotation={[-0.04, -0.02, 0.51]} scale={0.08}>
            <T.Mesh
              name="particle049_0_47"
              geometry={gltf.nodes.particle049_0_47.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle047" position={[0.14, -0.33, 0.08]} rotation={[-0.01, -0.03, 1.16]} scale={0.05}>
            <T.Mesh
              name="particle049_0_48"
              geometry={gltf.nodes.particle049_0_48.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="particle048" position={[0.88, -0.77, 0.67]} rotation={[0.07, 0.03, 1.49]} scale={0.05}>
            <T.Mesh
              name="particle049_0_49"
              geometry={gltf.nodes.particle049_0_49.geometry}
              material={rootMaterial}
            />
          </T.Group>
          <T.Group name="Point">
            <T.Group name="Point_1" />
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
